// <auto-generated />
using System;
using System.Collections.Generic;
using MainBackend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace MainBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DocumentCourses", b =>
                {
                    b.Property<int>("CoursesCourseId")
                        .HasColumnType("integer");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer");

                    b.HasKey("CoursesCourseId", "DocumentId");

                    b.HasIndex("DocumentId");

                    b.ToTable("DocumentCourses");
                });

            modelBuilder.Entity("LecturerCourses", b =>
                {
                    b.Property<int>("CoursesCourseId")
                        .HasColumnType("integer");

                    b.Property<int>("LecturersUserId")
                        .HasColumnType("integer");

                    b.HasKey("CoursesCourseId", "LecturersUserId");

                    b.HasIndex("LecturersUserId");

                    b.ToTable("LecturerCourses");
                });

            modelBuilder.Entity("MainBackend.Models.BackgroundWorker.BackgroundJob", b =>
                {
                    b.Property<Guid>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("BusinessData")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CuratedQaId")
                        .HasColumnType("integer");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceEntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("VerifiableQaId")
                        .HasColumnType("integer");

                    b.HasKey("JobId");

                    b.HasIndex("CuratedQaId");

                    b.HasIndex("VerifiableQaId");

                    b.ToTable("BackgroundJobs", t =>
                        {
                            t.HasCheckConstraint("CK_BackgroundJobs_ValidSourceEntity", "(\"SourceEntityType\" = 'verifiable_qa'\n    AND \"VerifiableQaId\" IS NOT NULL\n    AND \"CuratedQaId\" IS NULL)\nOR\n(\"SourceEntityType\" = 'curated_qa'\n    AND \"CuratedQaId\" IS NOT NULL\n    AND \"VerifiableQaId\" IS NULL)");
                        });
                });

            modelBuilder.Entity("MainBackend.Models.BackgroundWorker.BackgroundJobLog", b =>
                {
                    b.Property<Guid>("BackgroundJobLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BackgroundJobLogId");

                    b.HasIndex("JobId");

                    b.ToTable("BackgroundJobLogs");
                });

            modelBuilder.Entity("MainBackend.Models.Chat", b =>
                {
                    b.Property<Guid>("ChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChatTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastMessageAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("ChatId");

                    b.HasIndex("UserId");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("MainBackend.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CourseId"));

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("MainBackend.Models.CuratedQa", b =>
                {
                    b.Property<int>("CuratedQaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CuratedQaId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CuratedAnswer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CuratedQuestion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("VerifiableQaId")
                        .HasColumnType("integer");

                    b.HasKey("CuratedQaId");

                    b.HasIndex("VerifiableQaId");

                    b.ToTable("CuratedQas");
                });

            modelBuilder.Entity("MainBackend.Models.Document", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DocumentId"));

                    b.Property<string>("ContentType")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginalFileName")
                        .HasColumnType("text");

                    b.Property<string>("ProcessingMessage")
                        .HasColumnType("text");

                    b.Property<int>("ProcessingProgress")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ProcessingRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessingUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StorageKey")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DocumentId");

                    b.HasIndex("UserId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("MainBackend.Models.Major", b =>
                {
                    b.Property<int>("MajorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MajorId"));

                    b.Property<string>("MajorCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MajorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MajorId");

                    b.ToTable("Majors");
                });

            modelBuilder.Entity("MainBackend.Models.MatchingPair", b =>
                {
                    b.Property<Guid>("MatchingPairId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CuratedQaId")
                        .HasColumnType("integer");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1536)");

                    b.Property<string>("LeftText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RelationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RightText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MatchingPairId");

                    b.HasIndex("CuratedQaId");

                    b.HasIndex("Embedding")
                        .HasAnnotation("Npgsql:StorageParameter:ef_construction", 64)
                        .HasAnnotation("Npgsql:StorageParameter:m", 16);

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.ToTable("MatchingPairs");
                });

            modelBuilder.Entity("MainBackend.Models.Message", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<List<RagSegment>>("MessageSegments")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SenderType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.Property<int?>("VerifiableQaId")
                        .HasColumnType("integer");

                    b.HasKey("MessageId");

                    b.HasIndex("ChatId");

                    b.HasIndex("UserId");

                    b.HasIndex("VerifiableQaId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("MainBackend.Models.QuestionItem", b =>
                {
                    b.Property<Guid>("QuestionItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CuratedQaId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("QuestionData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("QuestionItemId");

                    b.HasIndex("CuratedQaId");

                    b.ToTable("QuestionItems");
                });

            modelBuilder.Entity("MainBackend.Models.QuestionResponse", b =>
                {
                    b.Property<Guid>("QuestionResponseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuestionItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReviewSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("StudentAnswer")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("QuestionResponseId");

                    b.HasIndex("QuestionItemId");

                    b.HasIndex("ReviewSessionId");

                    b.ToTable("QuestionResponses");
                });

            modelBuilder.Entity("MainBackend.Models.ReviewSession", b =>
                {
                    b.Property<Guid>("ReviewSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CorrectAnswers")
                        .HasColumnType("integer");

                    b.Property<int?>("CourseId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("ReviewSessionId");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId");

                    b.ToTable("ReviewSessions");
                });

            modelBuilder.Entity("MainBackend.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cohort")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("MajorId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("MajorId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MainBackend.Models.VerifiableQa", b =>
                {
                    b.Property<int>("VerifiableQaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VerifiableQaId"));

                    b.Property<string>("ApprovedAnswer")
                        .HasColumnType("text");

                    b.Property<int?>("ApprovedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1536)");

                    b.Property<string>("GeneratedAnswer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginalQuestion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RewrittenQuestion")
                        .HasColumnType("text");

                    b.Property<Guid>("SourceMessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("VerifiableQaId");

                    b.HasIndex("Embedding")
                        .HasAnnotation("Npgsql:StorageParameter:ef_construction", 64)
                        .HasAnnotation("Npgsql:StorageParameter:m", 16);

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("SourceMessageId")
                        .IsUnique();

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("UserId");

                    b.ToTable("VerifiableQas");
                });

            modelBuilder.Entity("VerifiableQaCourses", b =>
                {
                    b.Property<int>("CoursesCourseId")
                        .HasColumnType("integer");

                    b.Property<int>("VerifiableQaId")
                        .HasColumnType("integer");

                    b.HasKey("CoursesCourseId", "VerifiableQaId");

                    b.HasIndex("VerifiableQaId");

                    b.ToTable("VerifiableQaCourses");
                });

            modelBuilder.Entity("DocumentCourses", b =>
                {
                    b.HasOne("MainBackend.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("CoursesCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MainBackend.Models.Document", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LecturerCourses", b =>
                {
                    b.HasOne("MainBackend.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("CoursesCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MainBackend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("LecturersUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MainBackend.Models.BackgroundWorker.BackgroundJob", b =>
                {
                    b.HasOne("MainBackend.Models.CuratedQa", "CuratedQa")
                        .WithMany()
                        .HasForeignKey("CuratedQaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MainBackend.Models.VerifiableQa", "VerifiableQa")
                        .WithMany()
                        .HasForeignKey("VerifiableQaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CuratedQa");

                    b.Navigation("VerifiableQa");
                });

            modelBuilder.Entity("MainBackend.Models.BackgroundWorker.BackgroundJobLog", b =>
                {
                    b.HasOne("MainBackend.Models.BackgroundWorker.BackgroundJob", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("MainBackend.Models.Chat", b =>
                {
                    b.HasOne("MainBackend.Models.User", "User")
                        .WithMany("Chats")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MainBackend.Models.CuratedQa", b =>
                {
                    b.HasOne("MainBackend.Models.VerifiableQa", "VerifiableQa")
                        .WithMany("CuratedQas")
                        .HasForeignKey("VerifiableQaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VerifiableQa");
                });

            modelBuilder.Entity("MainBackend.Models.Document", b =>
                {
                    b.HasOne("MainBackend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MainBackend.Models.MatchingPair", b =>
                {
                    b.HasOne("MainBackend.Models.CuratedQa", "CuratedQa")
                        .WithMany()
                        .HasForeignKey("CuratedQaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CuratedQa");
                });

            modelBuilder.Entity("MainBackend.Models.Message", b =>
                {
                    b.HasOne("MainBackend.Models.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MainBackend.Models.User", "User")
                        .WithMany("Messages")
                        .HasForeignKey("UserId");

                    b.HasOne("MainBackend.Models.VerifiableQa", "VerifiableQa")
                        .WithMany()
                        .HasForeignKey("VerifiableQaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Chat");

                    b.Navigation("User");

                    b.Navigation("VerifiableQa");
                });

            modelBuilder.Entity("MainBackend.Models.QuestionItem", b =>
                {
                    b.HasOne("MainBackend.Models.CuratedQa", "CuratedQa")
                        .WithMany()
                        .HasForeignKey("CuratedQaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CuratedQa");
                });

            modelBuilder.Entity("MainBackend.Models.QuestionResponse", b =>
                {
                    b.HasOne("MainBackend.Models.QuestionItem", "QuestionItem")
                        .WithMany("QuestionResponses")
                        .HasForeignKey("QuestionItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MainBackend.Models.ReviewSession", "ReviewSession")
                        .WithMany("QuestionResponses")
                        .HasForeignKey("ReviewSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestionItem");

                    b.Navigation("ReviewSession");
                });

            modelBuilder.Entity("MainBackend.Models.ReviewSession", b =>
                {
                    b.HasOne("MainBackend.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId");

                    b.HasOne("MainBackend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MainBackend.Models.User", b =>
                {
                    b.HasOne("MainBackend.Models.Major", "Major")
                        .WithMany()
                        .HasForeignKey("MajorId");

                    b.Navigation("Major");
                });

            modelBuilder.Entity("MainBackend.Models.VerifiableQa", b =>
                {
                    b.HasOne("MainBackend.Models.Message", "SourceMessage")
                        .WithOne()
                        .HasForeignKey("MainBackend.Models.VerifiableQa", "SourceMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MainBackend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.HasOne("MainBackend.Models.User", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SourceMessage");

                    b.Navigation("ApprovedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VerifiableQaCourses", b =>
                {
                    b.HasOne("MainBackend.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("CoursesCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MainBackend.Models.VerifiableQa", null)
                        .WithMany()
                        .HasForeignKey("VerifiableQaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MainBackend.Models.Chat", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("MainBackend.Models.QuestionItem", b =>
                {
                    b.Navigation("QuestionResponses");
                });

            modelBuilder.Entity("MainBackend.Models.ReviewSession", b =>
                {
                    b.Navigation("QuestionResponses");
                });

            modelBuilder.Entity("MainBackend.Models.User", b =>
                {
                    b.Navigation("Chats");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("MainBackend.Models.VerifiableQa", b =>
                {
                    b.Navigation("CuratedQas");
                });
#pragma warning restore 612, 618
        }
    }
}
